### ISSUE TITLE
java.lang.NoClassDefFoundError: rx.schedulers.Schedulers

### ISSUE THREAD

**Issue by mateushenriquebrum** [j256/ormlite-android#65]
compile 'com.j256.ormlite:ormlite-android:4.48'
compile 'com.j256.ormlite:ormlite-core:4.48'
compile 'io.reactivex:rxandroid:1.1.0'
compile 'io.reactivex:rxjava:1.1.0'

For a strange cause, I am getting "java.lang.NoClassDefFoundError: rx.schedulers.Schedulers" when I try to compile in a device with Android 4.4.4, api 19 and ORMLite. 
I don't have such problem without ORMLite nor in device with api 23.

Some one know why my "reactive package" is bing excluded from my apk ?

**Comment by ShreyashPromact** [comment]
I am facing same issue with LoogerFactory class.
`Caused by: java.lang.NoClassDefFoundError: com.j256.ormlite.logger.LoggerFactory`

Anyone what is the solution to this issue?

Sincerely,
Shreyash

**Comment by j256** [comment]
This is a different issue @ShreyashPromact .  You are most likely missing the core library.  RTFM.

**Comment by ShreyashPromact** [comment]
@j256 
I have added core library in the project. Anyway, The issue is because of the multi dex. I have import the project from eclipse to Android studio and then I got this issue. When I have added multi dex properly and it is resolved now.

Thanks.

**Comment by gilokimu** [comment]
NoClassDefFoundError often happens when the build tools and/or hot-swapping fails to update after changing dependencies.

Try a Build > Clean Project and then run again.

**Comment by JianxunRao** [comment]
@mateushenriquebrum  Try custom the public class `MyApplication` extends **MultiDexApplication**

**Comment by j256** [comment]
I don't think this a ORMLite issue.
